namespace AnswerCode.Models;

/// <summary>
/// Text response and token usage from an LLM chat round.
/// </summary>
public class LLMChatResponse
{
    /// <summary>
    /// Text content returned by the model.
    /// </summary>
    public string? TextContent { get; init; }

    /// <summary>
    /// Number of input (prompt) tokens consumed by this LLM call.
    /// </summary>
    public int InputTokens { get; init; }

    /// <summary>
    /// Number of output (completion) tokens generated by this LLM call.
    /// </summary>
    public int OutputTokens { get; init; }
}
